"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { get, patch, post } from "@/lib/api";
import type { CurrentUser } from "@/lib/auth";
import type { Paged } from "@/lib/types";

type User = { id:number; email:string; displayName:string; party:string; roleId:number; roleName:string; roleIds:number[]; roleNames:string[]; organizationId:number|null; organizationName:string|null; active:boolean };
type Role = { id:number; name:string; party:"CLIENT"|"TICKETFLOW1"; template?:boolean };
type Organization = { id:number; name:string };

export default function UsersPage() { return <AppShell require="USER_MANAGE">{user => <UserAdmin current={user} />}</AppShell>; }

function UserAdmin({ current }: { current: CurrentUser }) {
  const [users, setUsers] = useState<User[]>([]); const [createRoles, setCreateRoles] = useState<Role[]>([]); const [assignmentRoles, setAssignmentRoles] = useState<Role[]>([]); const [organizations, setOrganizations] = useState<Organization[]>([]);
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [displayName,setDisplayName]=useState(""); const [roleId,setRoleId]=useState("");
  const [createOrganizationId,setCreateOrganizationId]=useState(current.organizationId?.toString() ?? ""); const [assignmentOrganizationId,setAssignmentOrganizationId]=useState(current.organizationId?.toString() ?? ""); const [message,setMessage]=useState("");
  const [selectedUserId,setSelectedUserId]=useState("");
  const [draftRoles,setDraftRoles]=useState<Record<number,number[]>>({}); const [savingUser,setSavingUser]=useState<number|null>(null);
  const loadUsers=useCallback(()=>get<Paged<User>>("/admin/users?pageSize=100").then(r=>{setUsers(r.items);setDraftRoles(Object.fromEntries(r.items.map(u=>[u.id,u.roleIds?.length?u.roleIds:[u.roleId]])));}),[]);
  useEffect(()=>{void loadUsers(); if(current.party==="TICKETFLOW1") void get<Organization[]>("/admin/organizations").then(setOrganizations);},[current.party,loadUsers]);
  useEffect(()=>{const query=createOrganizationId?`?organizationId=${createOrganizationId}`:"";void get<Role[]>(`/reference/assignable-roles${query}`).then(value=>{setCreateRoles(value);setRoleId("");});},[createOrganizationId]);
  useEffect(()=>{const query=assignmentOrganizationId?`?organizationId=${assignmentOrganizationId}`:"";setSelectedUserId("");void get<Role[]>(`/reference/assignable-roles${query}`).then(setAssignmentRoles);},[assignmentOrganizationId]);
  async function submit(e:FormEvent){e.preventDefault();setMessage("");try{const selected=createRoles.find(r=>r.id===Number(roleId));await post("/admin/users",{email,password,displayName,roleId:Number(roleId),organizationId:selected?.party==="CLIENT"?Number(createOrganizationId):null});setEmail("");setPassword("");setDisplayName("");setMessage("User created.");await loadUsers();}catch(e){setMessage(e instanceof Error?e.message:"Could not create user");}}
  function toggleRole(userId:number,id:number){setDraftRoles(all=>{const values=all[userId]??[];return {...all,[userId]:values.includes(id)?values.filter(value=>value!==id):[...values,id]}})}
  async function saveRoles(person:User){const roleIds=draftRoles[person.id]??[];if(!roleIds.length){setMessage("Every user must have at least one role.");return}setSavingUser(person.id);try{await patch(`/admin/users/${person.id}/role`,{roleIds});setMessage(`${person.displayName}'s roles were updated. They apply after the next sign-in.`);await loadUsers()}catch(e){setMessage(e instanceof Error?e.message:"Could not update roles.")}finally{setSavingUser(null)}}
  const scopedUsers=users.filter(u=>assignmentOrganizationId?u.organizationId===Number(assignmentOrganizationId):u.organizationId===null);
  const selectedUser=scopedUsers.find(u=>u.id===Number(selectedUserId));
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">User administration</h1><p className="text-slate-600">Roles are loaded from the server, so only roles you may assign are shown.</p></div>
    <form className="card grid gap-4 md:grid-cols-2" onSubmit={submit}><label>Display name<input className="field mt-1" required value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label>Email<input className="field mt-1" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Temporary password<input className="field mt-1" type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{current.party==="TICKETFLOW1"?<label>Organization for new user<select className="field mt-1" value={createOrganizationId} onChange={e=>setCreateOrganizationId(e.target.value)}><option value="">TicketFlow1 (internal)</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>:null}<label>Assignable role<select className="field mt-1" required value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="">Select a role</option>{createRoles.map(r=><option key={r.id} value={r.id}>{r.name} ({r.party})</option>)}</select></label><div className="self-end"><button className="btn-primary">Create user</button></div>{message?<p role="status" className="md:col-span-2">{message}</p>:null}</form>
    <section className="card"><div className="mb-4"><p className="eyebrow">User assignments</p><h2 className="mt-1 text-xl font-bold">Edit a user’s roles</h2><p className="mt-1 text-sm text-slate-500">Choose a separate user scope, select one user, then assign one or more roles.</p></div><div className="grid max-w-3xl gap-4 md:grid-cols-2">{current.party==="TICKETFLOW1"?<label>Users from<select className="field mt-1" value={assignmentOrganizationId} onChange={e=>setAssignmentOrganizationId(e.target.value)}><option value="">TicketFlow1 (internal)</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>:null}<label>User<select className="field mt-1" value={selectedUserId} onChange={e=>setSelectedUserId(e.target.value)}><option value="">Select a user</option>{scopedUsers.map(u=><option key={u.id} value={u.id}>{u.displayName} · {u.email}</option>)}</select></label></div>{selectedUser?<article className="mt-4 rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="block">{selectedUser.displayName}</strong><span className="text-xs text-slate-500">{selectedUser.email} · {selectedUser.organizationName??"TicketFlow1"} · {selectedUser.active?"Active":"Inactive"}</span></div><button className="btn-primary" disabled={savingUser===selectedUser.id||!(draftRoles[selectedUser.id]?.length)} onClick={()=>void saveRoles(selectedUser)}>{savingUser===selectedUser.id?"Saving…":"Save roles"}</button></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{assignmentRoles.map(r=><label className={`permission-option ${(draftRoles[selectedUser.id]??[]).includes(r.id)?"permission-option-selected":""}`} key={r.id}><input type="checkbox" checked={(draftRoles[selectedUser.id]??[]).includes(r.id)} onChange={()=>toggleRole(selectedUser.id,r.id)}/><span><strong>{r.name}</strong><small>{r.template?"Default role":"Custom role"}</small></span></label>)}</div></article>:<p className="mt-4 rounded-lg border border-dashed p-5 text-center text-sm text-slate-500">Select a user to edit their roles.</p>}</section></div>;
}
