"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { get, patch, post } from "@/lib/api";
import type { CurrentUser } from "@/lib/auth";
import type { Paged } from "@/lib/types";

type User = { id:number; email:string; displayName:string; party:string; roleId:number; roleName:string; roleIds:number[]; roleNames:string[]; organizationId:number|null; organizationName:string|null; active:boolean };
type Role = { id:number; name:string; party:"CLIENT"|"TICKETFLOW1"; template?:boolean };
type Organization = { id:number; name:string };

export default function UsersPage() { return <AppShell require="USER_MANAGE">{user => <UserAdmin current={user} />}</AppShell>; }

function UserAdmin({ current }: { current: CurrentUser }) {
  const [users, setUsers] = useState<User[]>([]); const [roles, setRoles] = useState<Role[]>([]); const [organizations, setOrganizations] = useState<Organization[]>([]);
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [displayName,setDisplayName]=useState(""); const [roleId,setRoleId]=useState("");
  const [organizationId,setOrganizationId]=useState(current.organizationId?.toString() ?? ""); const [message,setMessage]=useState("");
  const [draftRoles,setDraftRoles]=useState<Record<number,number[]>>({}); const [savingUser,setSavingUser]=useState<number|null>(null);
  const loadUsers=useCallback(()=>get<Paged<User>>("/admin/users?pageSize=100").then(r=>{setUsers(r.items);setDraftRoles(Object.fromEntries(r.items.map(u=>[u.id,u.roleIds?.length?u.roleIds:[u.roleId]])));}),[]);
  useEffect(()=>{void loadUsers(); if(current.party==="TICKETFLOW1") void get<Organization[]>("/admin/organizations").then(setOrganizations);},[current.party,loadUsers]);
  useEffect(()=>{const query=organizationId?`?organizationId=${organizationId}`:"";void get<Role[]>(`/reference/assignable-roles${query}`).then(value=>{setRoles(value);setRoleId("");});},[organizationId]);
  async function submit(e:FormEvent){e.preventDefault();setMessage("");try{const selected=roles.find(r=>r.id===Number(roleId));await post("/admin/users",{email,password,displayName,roleId:Number(roleId),organizationId:selected?.party==="CLIENT"?Number(organizationId):null});setEmail("");setPassword("");setDisplayName("");setMessage("User created.");await loadUsers();}catch(e){setMessage(e instanceof Error?e.message:"Could not create user");}}
  function toggleRole(userId:number,id:number){setDraftRoles(all=>{const values=all[userId]??[];return {...all,[userId]:values.includes(id)?values.filter(value=>value!==id):[...values,id]}})}
  async function saveRoles(person:User){const roleIds=draftRoles[person.id]??[];if(!roleIds.length){setMessage("Every user must have at least one role.");return}setSavingUser(person.id);try{await patch(`/admin/users/${person.id}/role`,{roleIds});setMessage(`${person.displayName}'s roles were updated. They apply after the next sign-in.`);await loadUsers()}catch(e){setMessage(e instanceof Error?e.message:"Could not update roles.")}finally{setSavingUser(null)}}
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">User administration</h1><p className="text-slate-600">Roles are loaded from the server, so only roles you may assign are shown.</p></div>
    <form className="card grid gap-4 md:grid-cols-2" onSubmit={submit}><label>Display name<input className="field mt-1" required value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label>Email<input className="field mt-1" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Temporary password<input className="field mt-1" type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{current.party==="TICKETFLOW1"?<label>Organization<select className="field mt-1" value={organizationId} onChange={e=>setOrganizationId(e.target.value)}><option value="">TicketFlow1 (internal)</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>:null}<label>Assignable role<select className="field mt-1" required value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="">Select a role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name} ({r.party})</option>)}</select></label><div className="self-end"><button className="btn-primary">Create user</button></div>{message?<p role="status" className="md:col-span-2">{message}</p>:null}</form>
    <section className="card"><div className="mb-4"><p className="eyebrow">User assignments</p><h2 className="mt-1 text-xl font-bold">Users and their roles</h2><p className="mt-1 text-sm text-slate-500">Select an organization above to load its default and custom roles, then assign one or more to a user.</p></div><div className="space-y-3">{users.filter(u=>organizationId?u.organizationId===Number(organizationId):u.organizationId===null).map(u=><article className="rounded-lg border p-4" key={u.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="block">{u.displayName}</strong><span className="text-xs text-slate-500">{u.email} · {u.organizationName??"TicketFlow1"} · {u.active?"Active":"Inactive"}</span></div><button className="btn-primary" disabled={savingUser===u.id||!(draftRoles[u.id]?.length)} onClick={()=>void saveRoles(u)}>{savingUser===u.id?"Saving…":"Save roles"}</button></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{roles.map(r=><label className={`permission-option ${(draftRoles[u.id]??[]).includes(r.id)?"permission-option-selected":""}`} key={r.id}><input type="checkbox" checked={(draftRoles[u.id]??[]).includes(r.id)} onChange={()=>toggleRole(u.id,r.id)}/><span><strong>{r.name}</strong><small>{r.template?"Default role":"Custom role"}</small></span></label>)}</div></article>)}</div></section></div>;
}
