package com.ticketflow1.ticketing.audit;

public enum AuditAction {
    TICKET_CREATED,
    STATUS_CHANGED,
    ASSIGNEE_CHANGED,
    COMMENT_ADDED,
    PROPOSAL_CREATED,
    PROPOSAL_APPROVED,
    PROPOSAL_REJECTED,
    SEVERITY_CHANGED,
    PRIORITY_CHANGED,
    ATTACHMENT_ADDED,
    DYNAMIC_FIELDS_CAPTURED,
    CORRECTION_RETURN,
    TICKET_UPDATED,
    CONFIG_CHANGED
}
