"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { get, patch, post } from "@/lib/api";
import type { CurrentUser } from "@/lib/auth";

type Role={id:number;name:string;party:"CLIENT"|"TICKETFLOW1";organizationId:number|null;template:boolean;permissions:string[]};
type Permission={id:number;key:string}; type Organization={id:number;name:string};
const permissionInfo:Record<string,{label:string;description:string;group:string}>={
  TICKET_READ:{label:"View tickets",description:"Open ticket lists, details and dashboards.",group:"Tickets"},TICKET_CREATE:{label:"Create tickets",description:"Submit new tickets for an organization.",group:"Tickets"},TICKET_UPDATE:{label:"Edit tickets",description:"Change ticket details, leads and attachments.",group:"Tickets"},TICKET_TRANSITION:{label:"Move tickets",description:"Use normal workflow actions.",group:"Tickets"},TICKET_CANCEL:{label:"Cancel tickets",description:"Move eligible tickets to Cancelled.",group:"Tickets"},
  COMMENT_PUBLIC_WRITE:{label:"Write public comments",description:"Communicate with both client and TicketFlow1 users.",group:"Communication"},COMMENT_INTERNAL_READ:{label:"View internal comments",description:"Read private TicketFlow1 notes.",group:"Communication"},COMMENT_INTERNAL_WRITE:{label:"Write internal comments",description:"Add private TicketFlow1 notes.",group:"Communication"},PROPOSAL_APPROVE:{label:"Decide proposals",description:"Approve or reject change proposals.",group:"Communication"},
  USER_MANAGE:{label:"Manage users",description:"Create users and assign their roles.",group:"Administration"},ROLE_MANAGE:{label:"Manage roles",description:"Create roles and change permission bundles.",group:"Administration"},TYPE_MANAGE:{label:"Manage ticket types",description:"Create and assign ticket types.",group:"Administration"},WORKFLOW_MANAGE:{label:"Manage workflows",description:"Build and edit workflow maps.",group:"Administration"}
};
const info=(key:string)=>permissionInfo[key]??{label:key.toLowerCase().replaceAll("_"," ").replace(/^./,c=>c.toUpperCase()),description:"System permission.",group:"Other"};

export default function RolesPage(){return <AppShell require="ROLE_MANAGE">{user=><RoleManager user={user}/>}</AppShell>}
function RoleManager({user}:{user:CurrentUser}){
  const [roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[organizations,setOrganizations]=useState<Organization[]>([]);
  const [scope,setScope]=useState(user.organizationId?String(user.organizationId):"internal"),[selected,setSelected]=useState<Role|null>(null),[creating,setCreating]=useState(false);
  const [name,setName]=useState(""),[keys,setKeys]=useState<string[]>([]),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{const query=scope==="internal"?"":`?organizationId=${scope}`;try{const rows=await get<Role[]>(`/admin/roles${query}`);setRoles(rows);setSelected(previous=>rows.find(role=>role.id===previous?.id)??null)}catch(error){setMessage(error instanceof Error?error.message:"Could not load roles.")}},[scope]);
  useEffect(()=>{void get<Permission[]>("/admin/permissions").then(setPermissions);if(user.party==="TICKETFLOW1")void get<Organization[]>("/admin/organizations").then(setOrganizations).catch(()=>setOrganizations([]))},[user.party]);
  useEffect(()=>{void load()},[load]);
  const groups=useMemo(()=>Object.entries(permissions.reduce<Record<string,Permission[]>>((result,permission)=>{const group=info(permission.key).group;(result[group]??=[]).push(permission);return result},{})),[permissions]);
  function choose(role:Role){setCreating(false);setSelected(role);setName(role.name);setKeys(role.permissions);setMessage("")}
  function beginCreate(){setCreating(true);setSelected(null);setName("");setKeys([]);setMessage("")}
  function toggle(key:string,checked:boolean){setKeys(current=>checked?[...current,key]:current.filter(item=>item!==key))}
  async function save(event:FormEvent){event.preventDefault();if(!name.trim()||!keys.length)return;setSaving(true);try{if(creating){await post("/admin/roles",{name:name.trim(),party:scope==="internal"?"TICKETFLOW1":"CLIENT",organizationId:scope==="internal"?null:Number(scope),permissionKeys:keys});setMessage("Custom role created and ready to assign to users.");setCreating(false)}else if(selected){await patch(`/admin/roles/${selected.id}`,{name:name.trim(),permissionKeys:keys});setMessage("Role saved. Users receive the new permissions after signing in again.")}await load()}catch(error){setMessage(error instanceof Error?error.message:"Could not save role.")}finally{setSaving(false)}}
  const locked=selected?.template===true;
  return <div className="space-y-5"><header><p className="eyebrow">Access control</p><h1 className="mt-1 text-3xl font-bold">Roles and permissions</h1><p className="mt-2 max-w-3xl text-slate-600">A role is a reusable access package assigned to users. Create a custom role or select an existing one, then choose what people with that role can do.</p></header>
    {user.party==="TICKETFLOW1"?<section className="card flex flex-wrap items-end gap-3 py-4"><label className="min-w-64 flex-1"><span className="text-xs font-bold uppercase tracking-wider text-slate-500">Role scope</span><select className="field mt-1" value={scope} onChange={event=>{setScope(event.target.value);setSelected(null);setCreating(false)}}><option value="internal">TicketFlow1 · all organizations</option>{organizations.map(org=><option key={org.id} value={org.id}>{org.name} · client roles</option>)}</select></label><button className="btn-primary" onClick={beginCreate}>+ Create custom role</button></section>:<div className="flex justify-end"><button className="btn-primary" onClick={beginCreate}>+ Create custom role</button></div>}
    <div className="grid gap-5 lg:grid-cols-[300px_minmax(0,1fr)]"><aside className="card self-start"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">Available roles</h2><span className="badge bg-slate-100 text-slate-700">{roles.length}</span></div><div className="space-y-2">{roles.map(role=><button key={role.id} className={`block w-full rounded-lg border p-3 text-left transition hover:bg-slate-50 ${selected?.id===role.id?"border-blue-500 bg-blue-950/30":""}`} onClick={()=>choose(role)}><div className="flex justify-between gap-2"><strong className="text-sm">{role.name}</strong>{role.template?<span className="text-[10px] text-slate-500">DEFAULT</span>:<span className="text-[10px] text-blue-400">CUSTOM</span>}</div><span className="mt-1 block text-xs text-slate-500">{role.permissions.length} permissions · {role.party==="CLIENT"?"Client":"TicketFlow1"}</span></button>)}</div></aside>
      <form className="card space-y-5" onSubmit={save}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">{creating?"New role":selected?"Edit role":"Role details"}</p><h2 className="mt-1 text-xl font-bold">{creating?"Create custom role":selected?.name??"Select a role"}</h2>{locked?<p className="mt-1 text-sm text-amber-300">This is a global default template. Select an organization’s cloned role to edit it.</p>:null}</div>{selected?<span className="badge bg-blue-900 text-blue-100">{selected.party==="CLIENT"?"Client scope":"Internal scope"}</span>:null}</div>
        <label className="block">Role name<input className="field mt-1" required disabled={(!selected&&!creating)||locked} value={name} placeholder="e.g. Support Coordinator" onChange={event=>setName(event.target.value)}/></label>
        <fieldset disabled={(!selected&&!creating)||locked}><legend className="mb-3 font-bold">What can this role do?</legend><div className="space-y-5">{groups.map(([group,items])=><section key={group}><h3 className="mb-2 text-xs font-bold uppercase tracking-wider text-blue-400">{group}</h3><div className="grid gap-2 md:grid-cols-2">{items?.map(permission=>{const meta=info(permission.key);return <label className={`permission-option ${keys.includes(permission.key)?"permission-option-selected":""}`} key={permission.id}><input type="checkbox" checked={keys.includes(permission.key)} onChange={event=>toggle(permission.key,event.target.checked)}/><span><strong>{meta.label}</strong><small>{meta.description}</small></span></label>})}</div></section>)}</div></fieldset>
        <div className="flex flex-wrap items-center gap-3"><button className="btn-primary" disabled={saving||locked||(!selected&&!creating)||!keys.length}>{saving?"Saving…":creating?"Create role":"Save changes"}</button>{creating?<button type="button" className="btn-secondary" onClick={()=>setCreating(false)}>Cancel</button>:null}<span className="text-xs text-slate-500">Permission changes apply after the user signs in again.</span></div>{message?<p className="rounded border p-3 text-sm" role="status">{message}</p>:null}</form>
    </div></div>
}
