"use client";
/**
 * Ticket list page.
 *
 * It wires the filter controls to the API query string and displays the paged
 * summary table returned by the backend.
 */
import Link from "next/link";
import { Suspense, useCallback, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { Pagination, SlaBadge, StatusBadge } from "@/components/TicketUi";
import { get } from "@/lib/api";
import type { Paged, TicketSummary } from "@/lib/types";
import { useTicketEvents } from "@/lib/realtime";

export default function TicketsPage() {
  return <AppShell require="TICKET_READ">{user => <Suspense fallback={<div className="card">Loading filters…</div>}><Tickets userId={user.id} /></Suspense>}</AppShell>;
}

function Tickets({ userId }: { userId: number }) {
  const query = useSearchParams(); const router = useRouter();
  const [data, setData] = useState<Paged<TicketSummary> | null>(null); const [error, setError] = useState("");
  const [showFilters, setShowFilters] = useState(false);
  type Draft = { q: string; lifecycle: string; type: string; subtype: string; parentTicketKey: string; severity: string; slaStatus: string; assignedTo: string; creatorId: string; view: string };
  const draftFromQuery = (): Draft => ({ q: query.get("q") ?? "", lifecycle: query.get("lifecycle") ?? "", type: query.get("type") ?? "", subtype: query.get("subtype") ?? "", parentTicketKey: query.get("parentTicketKey") ?? "", severity: query.get("severity") ?? "", slaStatus: query.get("slaStatus") ?? "", assignedTo: query.get("assignedTo") ?? "", creatorId: query.get("creatorId") ?? "", view: query.get("view") ?? "all" });
  const [draft, setDraft] = useState<Draft>(() => draftFromQuery());
  const key = query.toString();
  const load = useCallback(() => { get<Paged<TicketSummary>>(`/tickets?${key}`).then(value => { setData(value); setError(""); }).catch(e => setError(e.message)); }, [key]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { setDraft(draftFromQuery()); }, [key]);
  useTicketEvents(load);
  function update(name: keyof Draft, value: string) { setDraft(current => ({ ...current, [name]: value })); }
  function apply() { const p = new URLSearchParams(); (Object.entries(draft) as [keyof Draft, string][]).forEach(([name, value]) => { if (value.trim()) p.set(name, value.trim()); }); p.set("page", "0"); router.push(`/tickets?${p}`); setShowFilters(false); }
  function clear() { const empty: Draft = { q: "", lifecycle: "", type: "", subtype: "", parentTicketKey: "", severity: "", slaStatus: "", assignedTo: "", creatorId: "", view: "all" }; setDraft(empty); router.push("/tickets?page=0"); }
  function setPage(value: string) { const p = new URLSearchParams(key); p.set("page", value); router.push(`/tickets?${p}`); }
  const activeFilters = (["q", "lifecycle", "type", "subtype", "parentTicketKey", "severity", "slaStatus", "assignedTo", "creatorId"] as const)
    .map(name => [name, query.get(name) ?? ""] as const).filter(([, value]) => value);
  function removeFilter(name: string) { const p = new URLSearchParams(key); p.delete(name); p.set("page", "0"); router.push(`/tickets?${p}`); }
  return <div><div className="flex items-end justify-between"><div><h1 className="text-3xl font-bold">Tickets</h1><p className="mt-1 text-slate-600">Search and filter the current ticket scope.</p></div><Link className="btn-primary" href="/tickets/new">New ticket</Link></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="card h-fit"><p className="eyebrow">Ticket view</p><nav className="mt-3 grid gap-2" aria-label="Ticket ownership views">{[["assigned","Assigned to me"],["created","Created by me"],["all","All tickets"]].map(([value,label])=><button type="button" key={value} className={`rounded-lg px-3 py-2 text-left text-sm font-semibold ${draft.view===value?"bg-blue-600 text-white":"btn-secondary"}`} onClick={()=>{const p=new URLSearchParams(key);p.delete("assignedTo");p.delete("creatorId");p.set("view",value);p.set("page","0");if(value==="assigned")p.set("assignedTo","me");if(value==="created")p.set("creatorId",String(userId));router.push(`/tickets?${p}`)}}>{label}</button>)}</nav></aside><div>
    <section className="card mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Filters</h2><p className="text-sm text-slate-500">Filters are applied only when you select Apply.</p></div><button type="button" className="btn-secondary" aria-expanded={showFilters} onClick={() => setShowFilters(value => !value)}>{showFilters ? "Hide filters" : "Show filters"}</button></div>{showFilters ? <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><label className="sm:col-span-2 lg:col-span-2"><span className="text-sm">Search tickets and people</span><input className="field mt-1" value={draft.q} placeholder="Key, title, organization, lead or developer..." onChange={e => update("q", e.target.value)} /></label><Filter label="Lifecycle" value={draft.lifecycle} onChange={v => update("lifecycle", v)} options={["active", "closed"]} /><Filter label="Type" value={draft.type} onChange={v => update("type", v)} options={["TASI", "USR", "DFCT", "REQ", "DEFECT"]} /><label><span className="text-sm">Subtype</span><input className="field mt-1" value={draft.subtype} placeholder="FIREWALL, MODIFY..." onChange={e => update("subtype", e.target.value.toUpperCase())} /></label><label><span className="text-sm">Parent key</span><input className="field mt-1" value={draft.parentTicketKey} placeholder="TKT-1234" onChange={e => update("parentTicketKey", e.target.value.toUpperCase())} /></label><Filter label="Severity" value={draft.severity} onChange={v => update("severity", v)} options={["SEV_1", "SEV_2", "SEV_3", "SEV_4"]} /><Filter label="SLA" value={draft.slaStatus} onChange={v => update("slaStatus", v)} options={["OK", "DUE_SOON", "BREACHED", "NOT_APPLICABLE"]} /><Filter label="Assigned" value={draft.assignedTo} onChange={v => update("assignedTo", v)} options={["me", "unassigned"]} /><div className="flex flex-wrap items-end gap-2 sm:col-span-2 lg:col-span-6"><button type="button" className="btn-primary" onClick={apply}>Apply filters</button><button type="button" className="btn-secondary" onClick={clear}>Clear</button></div></div> : null}</section>
    {activeFilters.length ? <div className="mt-4 flex flex-wrap items-center gap-2" aria-label="Active ticket filters"><span className="text-xs font-semibold uppercase tracking-wider text-slate-500">Active filters</span>{activeFilters.map(([name, value]) => <span className="inline-flex items-center gap-1 rounded-full border border-blue-500/40 bg-blue-950/40 px-2.5 py-1 text-xs text-blue-100" key={name}><span>{filterLabel(name)}: {filterValue(name, value)}</span><button type="button" className="rounded-full px-1 text-blue-200 hover:bg-blue-500/30" aria-label={`Remove ${filterLabel(name)} filter`} onClick={() => removeFilter(name)}>×</button></span>)}</div> : null}
    {error ? <div className="card mt-5 text-red-700">{error}</div> : !data ? <div className="card mt-5">Loading tickets...</div> : data.items.length === 0 ? <div className="card mt-5">No tickets match these filters.</div> : <><div className="mt-5 overflow-hidden rounded-xl border bg-white"><table className="w-full table-fixed text-left text-xs"><thead className="bg-slate-50"><tr>{["Key / ticket", "Type", "Subtype", "Parent", "Severity", "Status", "Team lead", "Developers", "SLA", "Updated"].map(h => <th className="break-words p-2 font-semibold sm:p-3" key={h}>{h}</th>)}</tr></thead><tbody>{data.items.map(t => <tr className="border-t align-top" key={t.ticketKey}><td className="break-words p-2 sm:p-3"><Link className="font-semibold hover:underline" href={`/tickets/${t.ticketKey}`}>{t.ticketKey}</Link><span className="mt-1 block break-words text-[11px] text-slate-500" title={t.title}>{t.title}</span>{t.targetUserDisplaySnapshot ? <span className="mt-1 block break-words text-[11px] text-blue-400">Target: {t.targetUserDisplaySnapshot}</span> : null}</td><td className="break-words p-2 sm:p-3">{t.type.replaceAll("_", " ")}</td><td className="break-words p-2 sm:p-3">{t.subtype ? t.subtype.replaceAll("_", " ") : <span className="text-[11px] text-slate-500">None</span>}</td><td className="break-words p-2 sm:p-3">{t.parentTicketKey ? <Link className="text-blue-400 hover:underline" href={`/tickets/${t.parentTicketKey}`}>{t.parentTicketKey}</Link> : <span className="text-[11px] text-slate-500">Top level</span>}</td><td className="break-words p-2 sm:p-3"><Severity value={t.severity} /></td><td className="break-words p-2 sm:p-3"><StatusBadge value={t.status} /></td><td className="break-words p-2 sm:p-3"><Person value={t.ticketLeadName} empty="Unassigned" /></td><td className="break-words p-2 sm:p-3"><Person value={t.developerNames?.join(", ")} empty="No developers" /></td><td className="break-words p-2 sm:p-3"><SlaBadge value={t.slaStatus} /></td><td className="break-words p-2 sm:p-3">{new Date(t.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div><Pagination page={data.page} totalPages={data.totalPages} onPage={p => setPage(String(p))} /></>}</div></div>
  </div>;
}
function filterLabel(name: string) { return ({ q: "Search", lifecycle: "Lifecycle", type: "Type", subtype: "Subtype", parentTicketKey: "Parent", severity: "Severity", slaStatus: "SLA", assignedTo: "Assigned", creatorId: "Creator" } as Record<string, string>)[name] ?? name; }
function filterValue(name: string, value: string) { if (name === "creatorId") return "Created by me"; if (name === "assignedTo" && value === "me") return "Assigned to me"; return value.replaceAll("_", " "); }
function Filter({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: string[] }) { return <label><span className="text-sm">{label}</span><select className="field mt-1" value={value} onChange={e => onChange(e.target.value)}><option value="">All</option>{options.map(o => <option key={o}>{o}</option>)}</select></label>; }
function Severity({ value }: { value: string | null }) { if (!value) return <span className="text-xs text-slate-500">Not applicable</span>; const color = value === "SEV_1" ? "bg-red-100 text-red-800" : value === "SEV_2" ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-700"; return <span className={`badge ${color}`}>{value.replace("_", " ")}</span>; }
function Person({ value, empty }: { value?: string | null; empty: string }) { return value ? <span className="block truncate text-xs font-semibold" title={value}>{value}</span> : <span className="text-xs text-slate-500">{empty}</span>; }
