"use client";
import Link from "next/link";
import { Suspense, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { Pagination, SlaBadge, StatusBadge } from "@/components/TicketUi";
import { get } from "@/lib/api";
import type { Paged, TicketSummary } from "@/lib/types";
import { useTicketEvents } from "@/lib/realtime";

type ColumnKey = "type"|"subtype"|"parent"|"severity"|"status"|"team"|"developers"|"creator"|"created"|"sla"|"updated";
const COLUMNS: {key:ColumnKey;label:string}[] = [
  {key:"type",label:"Type"},{key:"subtype",label:"Subtype"},{key:"parent",label:"Parent"},{key:"severity",label:"Severity"},
  {key:"status",label:"Status"},{key:"team",label:"Team lead"},{key:"developers",label:"Developers"},{key:"creator",label:"Created by"},
  {key:"created",label:"Created"},{key:"sla",label:"SLA"},{key:"updated",label:"Updated"},
];

export default function TicketsPage(){return <AppShell require="TICKET_READ">{user=><Suspense fallback={<div className="card">Loading filters…</div>}><Tickets userId={user.id}/></Suspense>}</AppShell>}
function Tickets({userId}:{userId:number}){
  const query=useSearchParams(); const router=useRouter(); const key=query.toString();
  const [data,setData]=useState<Paged<TicketSummary>|null>(null),[error,setError]=useState(""),[showFilters,setShowFilters]=useState(false),[showColumns,setShowColumns]=useState(false),[hidden,setHidden]=useState<ColumnKey[]>([]),[columnDraft,setColumnDraft]=useState<ColumnKey[]>([]);
  type Draft={q:string;lifecycle:string;type:string;subtype:string;parentTicketKey:string;severity:string;slaStatus:string;assignedTo:string;creatorId:string;createdFrom:string;createdTo:string;view:string};
  const draftFromQuery=():Draft=>({q:query.get("q")??"",lifecycle:query.get("lifecycle")??"",type:query.get("type")??"",subtype:query.get("subtype")??"",parentTicketKey:query.get("parentTicketKey")??"",severity:query.get("severity")??"",slaStatus:query.get("slaStatus")??"",assignedTo:query.get("assignedTo")??"",creatorId:query.get("creatorId")??"",createdFrom:query.get("createdFrom")??"",createdTo:query.get("createdTo")??"",view:query.get("view")??"all"});
  const [draft,setDraft]=useState<Draft>(()=>draftFromQuery());
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("ticketflow.ticket-columns")??"[]") as ColumnKey[];setHidden(saved);setColumnDraft(saved)}catch{}},[]);
  const load=useCallback(()=>{get<Paged<TicketSummary>>(`/tickets?${key}`).then(value=>{setData(value);setError("")}).catch(e=>setError(e.message))},[key]); useEffect(()=>{void load()},[load]); useEffect(()=>{setDraft(draftFromQuery())},[key]); useTicketEvents(load);
  function update(name:keyof Draft,value:string){setDraft(current=>({...current,[name]:value}))} function apply(){const p=new URLSearchParams();(Object.entries(draft) as [keyof Draft,string][]).forEach(([name,value])=>{if(value.trim())p.set(name,value.trim())});p.set("page","0");router.push(`/tickets?${p}`);setShowFilters(false)} function clear(){setDraft(draftFromQuery());router.push("/tickets?page=0")} function removeFilter(name:string){const p=new URLSearchParams(key);p.delete(name);p.set("page","0");router.push(`/tickets?${p}`)}
  const active=(["q","lifecycle","type","subtype","parentTicketKey","severity","slaStatus","assignedTo","creatorId","createdFrom","createdTo"] as const).map(name=>[name,query.get(name)??""] as const).filter(([,value])=>value);
  const visible=COLUMNS.filter(column=>!hidden.includes(column.key));
  function toggleColumn(column:ColumnKey){setColumnDraft(current=>current.includes(column)?current.filter(item=>item!==column):[...current,column])}
  function saveColumns(){setHidden(columnDraft);localStorage.setItem("ticketflow.ticket-columns",JSON.stringify(columnDraft));setShowColumns(false)}
  function cancelColumns(){setColumnDraft(hidden);setShowColumns(false)}
  return <div><div className="flex items-end justify-between"><div><h1 className="text-3xl font-bold">Tickets</h1><p className="mt-1 text-slate-600">Search and filter the current ticket scope.</p></div><div className="flex gap-2"><button type="button" className="btn-secondary" onClick={()=>{setColumnDraft(hidden);setShowColumns(value=>!value)}}>Customize columns</button><Link className="btn-primary" href="/tickets/new">New ticket</Link></div></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="card h-fit"><p className="eyebrow">Ticket view</p><nav className="mt-3 grid gap-2">{[["assigned","Assigned to me"],["created","Created by me"],["all","All tickets"]].map(([value,label])=><button type="button" key={value} className={`rounded-lg px-3 py-2 text-left text-sm font-semibold ${draft.view===value?"bg-blue-600 text-white":"btn-secondary"}`} onClick={()=>{const p=new URLSearchParams(key);p.delete("assignedTo");p.delete("creatorId");p.set("view",value);p.set("page","0");if(value==="assigned")p.set("assignedTo","me");if(value==="created")p.set("creatorId",String(userId));router.push(`/tickets?${p}`)}}>{label}</button>)}</nav></aside><div>
    <section className="card mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Filters</h2><p className="text-sm text-slate-500">Filter by ticket metadata including creator and creation date.</p></div><button type="button" className="btn-secondary" onClick={()=>setShowFilters(value=>!value)}>{showFilters?"Hide filters":"Show filters"}</button></div>{showFilters?<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><label className="sm:col-span-2 lg:col-span-2"><span>Search tickets and people</span><input className="field mt-1" value={draft.q} onChange={e=>update("q",e.target.value)} placeholder="Key, title, organization, lead or developer..."/></label><Filter label="Lifecycle" value={draft.lifecycle} onChange={v=>update("lifecycle",v)} options={["active","closed"]}/><Filter label="Type" value={draft.type} onChange={v=>update("type",v)} options={["TASI","USR","DFCT","REQ","DEFECT"]}/><label><span>Subtype</span><input className="field mt-1" value={draft.subtype} onChange={e=>update("subtype",e.target.value.toUpperCase())}/></label><label><span>Parent key</span><input className="field mt-1" value={draft.parentTicketKey} onChange={e=>update("parentTicketKey",e.target.value.toUpperCase())}/></label><Filter label="Severity" value={draft.severity} onChange={v=>update("severity",v)} options={["SEV_1","SEV_2","SEV_3","SEV_4"]}/><Filter label="SLA" value={draft.slaStatus} onChange={v=>update("slaStatus",v)} options={["OK","DUE_SOON","BREACHED","NOT_APPLICABLE"]}/><Filter label="Assigned" value={draft.assignedTo} onChange={v=>update("assignedTo",v)} options={["me","unassigned"]}/><label><span>Created from</span><input className="field mt-1" type="date" value={draft.createdFrom} onChange={e=>update("createdFrom",e.target.value)}/></label><label><span>Created to</span><input className="field mt-1" type="date" value={draft.createdTo} onChange={e=>update("createdTo",e.target.value)}/></label><div className="flex gap-2 sm:col-span-2 lg:col-span-6"><button type="button" className="btn-primary" onClick={apply}>Apply filters</button><button type="button" className="btn-secondary" onClick={clear}>Clear</button></div></div>:null}</section>
    {active.length?<div className="mt-4 flex flex-wrap gap-2" aria-label="Active ticket filters">{active.map(([name,value])=><span className="inline-flex items-center gap-1 rounded-full border border-blue-300/70 bg-blue-500/25 px-3 py-1.5 text-sm" key={name}>{filterLabel(name)}: {filterValue(name,value)}<button type="button" onClick={()=>removeFilter(name)} aria-label={`Remove ${name}`}>×</button></span>)}</div>:null}
    {showColumns?<div className="card mt-3"><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{COLUMNS.map(column=><label className="permission-option" key={column.key}><input type="checkbox" checked={!columnDraft.includes(column.key)} onChange={()=>toggleColumn(column.key)}/><span><strong>{column.label}</strong><small>Show in ticket list</small></span></label>)}</div><div className="mt-4 flex gap-2"><button type="button" className="btn-primary" onClick={saveColumns}>Save</button><button type="button" className="btn-secondary" onClick={cancelColumns}>Cancel</button></div></div>:null}
    {!data?<div className="card mt-5">{error||"Loading tickets..."}</div>:data.items.length===0?<div className="card mt-5">No tickets match these filters.</div>:<><div className="mt-5 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[1180px] text-left text-xs"><thead><tr><th>Key / ticket</th>{visible.map(column=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{data.items.map(ticket=><TicketRow key={ticket.ticketKey} ticket={ticket} visible={visible}/>)}</tbody></table></div><Pagination page={data.page} totalPages={data.totalPages} onPage={page=>{const p=new URLSearchParams(key);p.set("page",String(page));router.push(`/tickets?${p}`)}}/></>}
    </div></div></div>;
}
function TicketRow({ticket,visible}:{ticket:TicketSummary;visible:{key:ColumnKey;label:string}[]}){const cells:Record<ColumnKey,React.ReactNode>={type:ticket.type.replaceAll("_"," "),subtype:ticket.subtype?.replaceAll("_"," ")??"None",parent:ticket.parentTicketKey?<Link className="text-blue-500" href={`/tickets/${ticket.parentTicketKey}`}>{ticket.parentTicketKey}</Link>:"Top level",severity:<Severity value={ticket.severity}/>,status:<StatusBadge value={ticket.status}/>,team:<Person value={ticket.ticketLeadName} empty="Unassigned"/>,developers:<Person value={ticket.developerNames?.join(", ")} empty="No developers"/>,creator:<Person value={ticket.businessOwnerName} empty="Unknown"/>,created:formatDate(ticket.createdAt),sla:<SlaBadge value={ticket.slaStatus}/>,updated:formatDate(ticket.updatedAt)};return <tr className="border-t align-top"><td><Link className="font-semibold text-blue-500" href={`/tickets/${ticket.ticketKey}`}>{ticket.ticketKey}</Link><span className="block text-[11px] text-slate-500">{ticket.title}</span></td>{visible.map(column=><td key={column.key}>{cells[column.key]}</td>)}</tr>}
function filterLabel(name:string){return ({q:"Search",lifecycle:"Lifecycle",type:"Type",subtype:"Subtype",parentTicketKey:"Parent",severity:"Severity",slaStatus:"SLA",assignedTo:"Assigned",creatorId:"Creator",createdFrom:"Created from",createdTo:"Created to"} as Record<string,string>)[name]??name} function filterValue(name:string,value:string){if(name==="creatorId")return "Created by me";if(name==="assignedTo"&&value==="me")return "Assigned to me";return value.replaceAll("_"," ")} function formatDate(value:string){try{return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}catch{return value}}
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[]}){return <label><span>{label}</span><select className="field mt-1" value={value} onChange={e=>onChange(e.target.value)}><option value="">All</option>{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function Severity({value}:{value:string|null}){return value?<span className="badge">{value.replace("_"," ")}</span>:<span className="text-slate-500">Not applicable</span>} function Person({value,empty}:{value?:string|null;empty:string}){if(!value)return <span className="text-slate-500">{empty}</span>;const people=value.split(",").map(item=>item.trim()).filter(Boolean);return people.length>1?<details className="metadata-expander"><summary className="cursor-pointer truncate">{people[0]} <span className="text-blue-600">+{people.length-1}</span></summary><div className="metadata-expander-popover">{people.map(person=><span key={person}>{person}</span>)}</div></details>:<span className="block truncate" title={value}>{value}</span>}
