"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { AppShell } from "@/components/AppShell";
import { SlaBadge,StatusBadge } from "@/components/TicketUi";
import { ApiError,get } from "@/lib/api";

type Ticket={ticketKey:string;title:string;type:string;status:string;slaStatus:string};
type Dashboard={activeCount:number;closedCount:number;byType:Record<string,number>;byStatus:Record<string,number>;defectsBySeverity:Record<string,number>;slaBreached:Ticket[];slaDueSoon:Ticket[];waitingForClientApproval:Ticket[];waitingForClientConfirmation:Ticket[];myAssignedTickets:Ticket[]};

export default function DashboardPage(){return <AppShell require="TICKET_READ">{()=> <DashboardContent/>}</AppShell>}
function DashboardContent(){const [data,setData]=useState<Dashboard|null>(null);const [error,setError]=useState("");useEffect(()=>{get<Dashboard>("/dashboard").then(setData).catch(e=>setError(e instanceof ApiError?e.message:"Could not load dashboard."));},[]);if(error)return <div className="card text-red-700" role="alert">{error}</div>;if(!data)return <div className="card" role="status">Loading dashboard…</div>;return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-widest text-slate-500">Overview</p><h1 className="mt-1 text-3xl font-bold">Dashboard</h1></div><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Active tickets" value={data.activeCount}/><Metric label="Closed tickets" value={data.closedCount}/>{Object.entries(data.defectsBySeverity).map(([k,v])=><Metric key={k} label={k.replace("_"," ")} value={v}/>)}</section><section className="grid gap-6 lg:grid-cols-2"><TicketCard title="SLA breached" tickets={data.slaBreached} sla/><TicketCard title="SLA due soon" tickets={data.slaDueSoon} sla/><TicketCard title="Waiting for approval" tickets={data.waitingForClientApproval}/><TicketCard title="Waiting for confirmation" tickets={data.waitingForClientConfirmation}/>{data.myAssignedTickets.length?<TicketCard title="My assigned tickets" tickets={data.myAssignedTickets}/>:null}</section></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="card"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
function TicketCard({title,tickets,sla=false}:{title:string;tickets:Ticket[];sla?:boolean}){return <div className="card"><h2 className="text-lg font-bold">{title}</h2>{tickets.length===0?<p className="mt-4 text-sm text-slate-500">Nothing needs attention.</p>:<ul className="mt-3 divide-y">{tickets.map(t=><li className="py-3" key={t.ticketKey}><Link className="font-semibold hover:underline" href={`/tickets/${t.ticketKey}`}>{t.ticketKey} · {t.title}</Link><div className="mt-2 flex gap-2"><StatusBadge value={t.status}/>{sla?<SlaBadge value={t.slaStatus}/>:null}</div></li>)}</ul>}</div>}
